"""add sla due date to tickets

Revision ID: 7960b7732239
Revises: 2724e98c4ce1
Create Date: 2026-09-21 10:03:16.919286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7960b7732239'
down_revision: Union[str, Sequence[str], None] = '2724e98c4ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tickets_sla_due_at'), 'tickets', ['sla_due_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_sla_due_at'), table_name='tickets')
    op.drop_column('tickets', 'sla_due_at')
    # ### end Alembic commands ###
