# backend/app/core/audit_actions.py

class AuditAction:
    LOGIN = "LOGIN"
    FAILED_LOGIN = "FAILED_LOGIN"
    LOGOUT = "LOGOUT"

    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_ACTIVATED = "USER_ACTIVATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    ROLE_CHANGED = "ROLE_CHANGED"

    CATEGORY_CREATED = "CATEGORY_CREATED"
    CATEGORY_UPDATED = "CATEGORY_UPDATED"
    CATEGORY_ACTIVATED = "CATEGORY_ACTIVATED"
    CATEGORY_DEACTIVATED = "CATEGORY_DEACTIVATED"

    TICKET_CREATED = "TICKET_CREATED"
    TICKET_UPDATED = "TICKET_UPDATED"
    TICKET_DELETED = "TICKET_DELETED"

    TICKET_ASSIGNED = "TICKET_ASSIGNED"
    TICKET_UNASSIGNED = "TICKET_UNASSIGNED"

    STATUS_CHANGED = "STATUS_CHANGED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"

    COMMENT_CREATED = "COMMENT_CREATED"
    COMMENT_UPDATED = "COMMENT_UPDATED"
    COMMENT_DELETED = "COMMENT_DELETED"

    ATTACHMENT_CREATED = "ATTACHMENT_CREATED"
    ATTACHMENT_DELETED = "ATTACHMENT_DELETED"

    NOTIFICATION_CREATED = "NOTIFICATION_CREATED"

    SLA_BREACHED = "SLA_BREACHED"
    
    