
class AuditAction:
    TICKET_CREATED = "TICKET_CREATED"
    TICKET_UPDATED = "TICKET_UPDATED"
    TICKET_ASSIGNED = "TICKET_ASSIGNED"
    TICKET_UNASSIGNED = "TICKET_UNASSIGNED"
    STATUS_CHANGED = "STATUS_CHANGED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"

    COMMENT_CREATED = "COMMENT_CREATED"
    COMMENT_UPDATED = "comment_updated"
    COMMENT_DELETED = "comment_deleted"

    ATTACHMENT_CREATED = "ATTACHMENT_CREATED"
    ATTACHMENT_DELETED = "ATTACHMENT_DELETED"

    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"

    CATEGORY_CREATED = "CATEGORY_CREATED"
    CATEGORY_UPDATED = "CATEGORY_UPDATED"
    
    